import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Signup() {
    return (
        <>
           <Head>
                <title>EMS - Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <div>
                    <Link href="/">EMS</Link>
                </div>

                <div>
                    Burger menu
                </div>

                <div className='sidebar'>

                    <div>
                        Avatar
                    </div>
                    <div>
                        @username
                    </div>
                    <nav>
                        <ul>
                            <li>
                                Data
                                <ul>
                                    <li>Import Data</li>
                                    <li>Sync Data</li>
                                </ul>
                            </li>
                        </ul>
                    </nav>

                    <Link href='/'>Log out</Link>
                </div>
            </header>
            <main className={styles.main}>
                <h2>Your energy consumption</h2>

                <section className="carousel-chart">
                    <div>
                        &lsaquo; 
                    </div>

                    <div className='chart'>
                        Chart
                    </div>

                    <div>
                        &rsaquo;
                    </div>
                </section> 

                <section className='stat'>
                    <h3>Average consumption</h3>

                    34 kwh / day
                </section>

                <section className='stat'>
                    <h3>Recent Highest consumption</h3>

                    45 kwh within the last 30 days

                </section>

                
            </main>
            <footer>
                <p>&copy; 2023 Energy Management System</p>
            </footer>

        </>
    )
}