import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>EMS - Energy System Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>EMS</h1>
        <p>Manage your energy consumption</p>
      </header>
      <main className={styles.main}>

        <h2>Log In</h2>

        <form action="" method="post">
          <div>
            <label htmlFor="login">Email Address</label>
            <input type="text" name="login" id="login" placeholder='Email adress or Username'/>
          </div>
          <div>
            <label htmlFor="pswd">Password</label>
            <input type="password" name="pswd" id="pswd" />
          </div>

          <button type="submit">Log In</button>
        </form>

        <hr />

        <p>No account yet? <Link href="/signup">Sign up</Link></p>

     
      </main>

      <footer>
        <p>&copy; 2023 Energy Management System</p>
      </footer>
    </>
  )
}
