import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Layout from '@/components/Layout'
import LoginForm from '@/components/LoginForm'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

interface Props {}

const Home: React.FC<Props> = () => {
  return (
    <>
      <Head>
        <title>EMS - Energy System Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout home>
        <LoginForm />
      </Layout>
    </>
  )
}

export default Home;
