import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

interface Props {}

const Test: React.FC<Props> = () => {
    return (
        <>
            <Head>
                <title>EMS - Energy System Management</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                Hello world!
            </Layout>
        </>
    )
}

export default Test;